config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  get '/test', to: proc { |el| [200, {},["ok"]]}
  get '/contact', to: "static_pages#contact"
  get '/about', to: "static_pages#about_us"
  get '/mission', to: "static_pages#mission"
  get '/help', to: "static_pages#help_me"
  root to: "users#index" 

  resources :users do 
    resources :orders
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def index; end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index
        @orders = Order.all
    end

    def show
        @order = Order.find(params[:id])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def contact; end

    def aboute_us; end

    def mission; end
    
    def help_me; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apka</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= yield %>

    <p class="notice"><%=notice%></p>
    <p class="alert"><%=alert%></p>
  </body>
</html>

app/views/orders/index.erb
<% @orders.each do |order| %>
<p><%= order.name %></p>
<% end %>

app/views/orders/show.erb
<%= @order.name %>

app/views/shared/_nav.haml
= link_to "Misja", mission_path 
= link_to "Contact", contact_path 
= link_to "Lonas", about_path 
= link_to "HELP", help_path 
= link_to "Users", users_path 
= link_to "Orders", orders_path 
- if current_user
  = link_to "Wyloguj", destroy_user_session_path, method: :delete    
- else 
  = link_to "Sign In", new_user_session_path 

app/views/static_pages/about_us.erb
<h1>About us</h1>

app/views/static_pages/contact.erb
<h1>contacta</h1>

app/views/static_pages/help_me.erb
<h1>I NEED MEDIC!!</h1>

app/views/static_pages/mission.erb
<h1>About us</h1>

app/views/users/index.erb
<% @users.each do |user| %>
<p><%= user.name %></p>
<% end %>

app/views/users/show.erb
<%= @user.name %>